"""add flush schedule

Revision ID: 8401689043f3
Revises: 330ae54039d4
Create Date: 2026-07-05 15:55:18.050754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8401689043f3'
down_revision: Union[str, Sequence[str], None] = '330ae54039d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('flush_interval_days', sa.Integer(), nullable=True))
    op.add_column('plant', sa.Column('next_flush_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'next_flush_date')
    op.drop_column('plant', 'flush_interval_days')
    # ### end Alembic commands ###
